---
 - hosts: loadbalancers
   become: true
   tasks:
     - name: Install apache
       apt: name=apache2 state=present
     - name: Ensure service starts
       service: name=apache2 state=started enabled=yes

 - hosts: webservers
   become: true
   tasks:
     - name: Install services
       apt:
         name:
           - apache2
           - php
         state: present
     - name: Ensure service starts
       service: name=apache2 state=started enabled=yes
